// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDBj3ow1txDfYqyPZYrIkbz8mMvsLK1YI',
    appId: '1:245539555685:web:44d1fefbd243636fdbf98c',
    messagingSenderId: '245539555685',
    projectId: 'edu-vesta',
    authDomain: 'edu-vesta.firebaseapp.com',
    storageBucket: 'edu-vesta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQF03__iLkCXPjZmMBEqPoesO5iaKV1GM',
    appId: '1:245539555685:android:a3fe60e0ec3f4eb6dbf98c',
    messagingSenderId: '245539555685',
    projectId: 'edu-vesta',
    storageBucket: 'edu-vesta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-wqbv3NR26_scqGBBj7IiuyM6G11WTo0',
    appId: '1:245539555685:ios:637b85329f3ec6cbdbf98c',
    messagingSenderId: '245539555685',
    projectId: 'edu-vesta',
    storageBucket: 'edu-vesta.appspot.com',
    iosBundleId: 'com.example.eduVesta',
  );
}
